"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ufactory_lite6_control_t(object):

    __slots__ = ["timestamp", "mode", "speed", "mvacc", "qj_tau", "qj_pos", "qj_vel", "kp", "kd", "v_ee", "ee_frame"]

    __typenames__ = ["int64_t", "int8_t", "double", "double", "double", "double", "double", "double", "double", "double", "boolean"]

    __dimensions__ = [None, None, None, None, [6], [6], [6], [6], [6], [6], None]

    num_joint = 6

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.mode = 0
        """
        Control mode: 
        0 = position/servo (target = qj_pos),
        1 = joint velocity/jog (target = qj_vel),
        2 = Cartesian velocity/jog (target = v_ee)
        LCM Type: int8_t
        """

        self.speed = 0.0
        """
        Trajectory shaping limits. Scalars.
        LCM Type: double
        """

        self.mvacc = 0.0
        """
        max joint speed (rad/s); <=0 means: no limit / track target directly in servo mode
        LCM Type: double
        """

        self.qj_tau = [ 0.0 for dim0 in range(6) ]
        """
        max joint acceleration (rad/s^2)
        Tau, kp, kd is currently unused by the Lite 6 bridge: the MuJoCo model is position-controlled,
        so the servo gains live in the XML. Kept for the generic torque bridge and a possible torque lab.
        LCM Type: double[6]
        """

        self.qj_pos = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.qj_vel = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.kp = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.kd = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.v_ee = [ 0.0 for dim0 in range(6) ]
        """
        For mode 2 only: end-effector twist [vx, vy, vz, wx, wy, wz] in m/s and rad/s.
        LCM Type: double[6]
        """

        self.ee_frame = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(ufactory_lite6_control_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbdd", self.timestamp, self.mode, self.speed, self.mvacc))
        buf.write(struct.pack('>6d', *self.qj_tau[:6]))
        buf.write(struct.pack('>6d', *self.qj_pos[:6]))
        buf.write(struct.pack('>6d', *self.qj_vel[:6]))
        buf.write(struct.pack('>6d', *self.kp[:6]))
        buf.write(struct.pack('>6d', *self.kd[:6]))
        buf.write(struct.pack('>6d', *self.v_ee[:6]))
        buf.write(struct.pack(">b", self.ee_frame))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ufactory_lite6_control_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ufactory_lite6_control_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ufactory_lite6_control_t()
        self.timestamp, self.mode, self.speed, self.mvacc = struct.unpack(">qbdd", buf.read(25))
        self.qj_tau = struct.unpack('>6d', buf.read(48))
        self.qj_pos = struct.unpack('>6d', buf.read(48))
        self.qj_vel = struct.unpack('>6d', buf.read(48))
        self.kp = struct.unpack('>6d', buf.read(48))
        self.kd = struct.unpack('>6d', buf.read(48))
        self.v_ee = struct.unpack('>6d', buf.read(48))
        self.ee_frame = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ufactory_lite6_control_t in parents: return 0
        tmphash = (0x7d28a7b6df2ccd1f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ufactory_lite6_control_t._packed_fingerprint is None:
            ufactory_lite6_control_t._packed_fingerprint = struct.pack(">Q", ufactory_lite6_control_t._get_hash_recursive([]))
        return ufactory_lite6_control_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ufactory_lite6_control_t._get_packed_fingerprint())[0]

