"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ufactory_lite6_state_t(object):

    __slots__ = ["timestamp", "qj_pos", "qj_vel", "qj_tau", "inertia_mat", "bias_force", "J_ee", "dJdq_ee", "p_ee"]

    __typenames__ = ["int64_t", "double", "double", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, [6], [6], [6], [6, 6], [6], [3, 6], [3], [3]]

    num_joint = 6

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.qj_pos = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.qj_vel = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.qj_tau = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.inertia_mat = [ [ 0.0 for dim1 in range(6) ] for dim0 in range(6) ]
        """ LCM Type: double[6][6] """
        self.bias_force = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.J_ee = [ [ 0.0 for dim1 in range(6) ] for dim0 in range(3) ]
        """
        End-effector translational Jacobian: [qj_vel] -> [v_ee]
        LCM Type: double[3][6]
        """

        self.dJdq_ee = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.p_ee = [ 0.0 for dim0 in range(3) ]
        """
        End-effector position in world frame
        LCM Type: double[3]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(ufactory_lite6_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>6d', *self.qj_pos[:6]))
        buf.write(struct.pack('>6d', *self.qj_vel[:6]))
        buf.write(struct.pack('>6d', *self.qj_tau[:6]))
        for i0 in range(6):
            buf.write(struct.pack('>6d', *self.inertia_mat[i0][:6]))
        buf.write(struct.pack('>6d', *self.bias_force[:6]))
        for i0 in range(3):
            buf.write(struct.pack('>6d', *self.J_ee[i0][:6]))
        buf.write(struct.pack('>3d', *self.dJdq_ee[:3]))
        buf.write(struct.pack('>3d', *self.p_ee[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ufactory_lite6_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ufactory_lite6_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ufactory_lite6_state_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.qj_pos = struct.unpack('>6d', buf.read(48))
        self.qj_vel = struct.unpack('>6d', buf.read(48))
        self.qj_tau = struct.unpack('>6d', buf.read(48))
        self.inertia_mat = []
        for i0 in range(6):
            self.inertia_mat.append(struct.unpack('>6d', buf.read(48)))
        self.bias_force = struct.unpack('>6d', buf.read(48))
        self.J_ee = []
        for i0 in range(3):
            self.J_ee.append(struct.unpack('>6d', buf.read(48)))
        self.dJdq_ee = struct.unpack('>3d', buf.read(24))
        self.p_ee = struct.unpack('>3d', buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ufactory_lite6_state_t in parents: return 0
        tmphash = (0x5d9f2caa75a9eb2b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ufactory_lite6_state_t._packed_fingerprint is None:
            ufactory_lite6_state_t._packed_fingerprint = struct.pack(">Q", ufactory_lite6_state_t._get_hash_recursive([]))
        return ufactory_lite6_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ufactory_lite6_state_t._get_packed_fingerprint())[0]

