"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ufactory_lite6_display_t(object):

    __slots__ = ["timestamp", "show_ghost", "ghost_qj_pos", "show_fk", "fk_pos", "fk_rpy"]

    __typenames__ = ["int64_t", "boolean", "double", "boolean", "double", "double"]

    __dimensions__ = [None, None, [6], None, [3], [3]]

    num_joint = 6

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.show_ghost = False
        """
        Ghost arm: translucent preview of an IK solution, drawn as a second copy
        of the robot at these joint angles.
        LCM Type: boolean
        """

        self.ghost_qj_pos = [ 0.0 for dim0 in range(6) ]
        """
        false clears the ghost overlay
        LCM Type: double[6]
        """

        self.show_fk = False
        """
        rad
        FK marker: translucent box + RGB axis triad at the pose the upper-level
        forward kinematics reports for the end effector.
        LCM Type: boolean
        """

        self.fk_pos = [ 0.0 for dim0 in range(3) ]
        """
        false clears the FK overlay
        LCM Type: double[3]
        """

        self.fk_rpy = [ 0.0 for dim0 in range(3) ]
        """
        m,   world frame
        LCM Type: double[3]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(ufactory_lite6_display_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.timestamp, self.show_ghost))
        buf.write(struct.pack('>6d', *self.ghost_qj_pos[:6]))
        buf.write(struct.pack(">b", self.show_fk))
        buf.write(struct.pack('>3d', *self.fk_pos[:3]))
        buf.write(struct.pack('>3d', *self.fk_rpy[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ufactory_lite6_display_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ufactory_lite6_display_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ufactory_lite6_display_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.show_ghost = bool(struct.unpack('b', buf.read(1))[0])
        self.ghost_qj_pos = struct.unpack('>6d', buf.read(48))
        self.show_fk = bool(struct.unpack('b', buf.read(1))[0])
        self.fk_pos = struct.unpack('>3d', buf.read(24))
        self.fk_rpy = struct.unpack('>3d', buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ufactory_lite6_display_t in parents: return 0
        tmphash = (0xe1384465fe083f7c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ufactory_lite6_display_t._packed_fingerprint is None:
            ufactory_lite6_display_t._packed_fingerprint = struct.pack(">Q", ufactory_lite6_display_t._get_hash_recursive([]))
        return ufactory_lite6_display_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ufactory_lite6_display_t._get_packed_fingerprint())[0]

